<!--
/**
 * Fam
 *
 * @category  Fam
 * @package   Fam_Fam
 * @author    Fam Team
 * @copyright Copyright (c) Frictionless Technologies Ltd (https://www.joinfam.com/)
 * @license   https://joinfam.com/legal
 */ 
 -->
<?php if ($block->getWebsiteId()) : ?>
    <?php if ($block->isOSMEnabled()) : ?>
        <div charset="utf-8" id="fam.js" data-merchant-id="<?= $block->getMerchantId()?>" data-environment="<?= $block->getPaymentMode()?>"></div>
        <script type="text/javascript">
            require(
                [
                    "jquery",
                    "https://cdnjs.cloudflare.com/ajax/libs/crypto-js/4.1.1/crypto-js.min.js",
                    "https://cdnjs.cloudflare.com/ajax/libs/dialog-polyfill/0.5.6/dialog-polyfill.min.js"
                ], 
                function ($,cryptoLib,dialogPolyFill) {
                    window.CryptoJS = cryptoLib;
                    window.dialogPolyfill = dialogPolyFill;
                    $.getScript("https://js.joinfam.com/v1/fam.js", function() {});
            });
        </script>
    <?php endif; ?>   
<?php endif; ?>   

