<?php
/**
 * Ksolves
 *
 * @category    Ksolves
 * @package     Ksolves_Fam
 * @author      Ksolves Team
 * @copyright   Copyright (c) Ksolves India Ltd.(https://www.ksolves.com/)
 * @license     https://store.ksolves.com/magento-license
 */

/** @var Ksolves\Fam\Block\Sales\Order\View\FamPaymentInfo $block */

$data = $block->getFamInformation(); 
?>
<div class="admin__page-section-item order-information">
    <div class="admin__page-section-item-content">
        <table class="admin__table-secondary fam-info">
            <tbody>
                <tr>
                    <?php if ($data->getData('transaction_id')) : ?>
                        <th><?php echo __('Transaction Id:') ?></th>
                        <td><?= $data->getData('transaction_id') ?></td>
                    <?php endif; ?>
                </tr>
                <tr>
                    <?php if ($data->getData('transaction_status')) : ?>
                        <th><?php echo __('Transaction Status:') ?></th>
                        <td><?= $data->getData('transaction_status') ?></td>
                    <?php endif; ?>
                </tr>
            </tbody>
        </table>
    </div>
</div>


<script type="text/javascript">
    require(['jquery'], function ($) {
        $('.box-order-billing-method').append($('.fam-info'));
    });
</script>

<div class="admin__page-section-item-content">
    <table class="admin__table-secondary order-account-information-table"></table>
</div>
