<?php
/**
 * Fam
 *
 * @category  Fam
 * @package   Fam_Fam
 * @author    Fam Team
 * @copyright Copyright (c) Frictionless Technologies Ltd (https://www.joinfam.com/)
 * @license   https://joinfam.com/legal
 */ 

/** @var Fam\Fam\Block\Sales\Order\View\FamPaymentInfo $block */

$data = $block->getFamInformation(); 
?>
<div class="admin__page-section-item order-information">
    <div class="admin__page-section-item-content">
        <table class="admin__table-secondary fam-info">
            <tbody>
                <tr>
                    <?php if ($data->getData('transaction_id')) : ?>
                        <th><?php echo __('Transaction Id:') ?></th>
                        <td><?= $data->getData('transaction_id') ?></td>
                    <?php endif; ?>
                </tr>
                <tr>
                    <?php if ($data->getData('transaction_status')) : ?>
                        <th><?php echo __('Transaction Status:') ?></th>
                        <td><?= $data->getData('transaction_status') ?></td>
                    <?php endif; ?>
                </tr>
            </tbody>
        </table>
    </div>
</div>


<script type="text/javascript">
    require(['jquery'], function ($) {
        $('.box-order-billing-method').append($('.fam-info'));
    });
</script>

<div class="admin__page-section-item-content">
    <table class="admin__table-secondary order-account-information-table"></table>
</div>
