<?php
/**
 * Ksolves
 *
 * @category    Ksolves
 * @package     Ksolves_Fam
 * @author      Ksolves Team
 * @copyright   Copyright (c) Ksolves India Ltd.(https://www.ksolves.com/)
 * @license     https://store.ksolves.com/magento-license
 */

/** @var $block \Ksolves\Fam\Block\OnsiteMessage */
?>
<?php if ($block->getWebsiteId()) : ?>
    <?php if ($block->isEnabled("product_detail_page")) : ?>

        <fam-osm data-widget-type="callout" data-currency="GBP" data-total-amount="<?= $block->getPriceById() * 100?>" data-theme="<?= $block->getThemeColour("product_detail_page")?>" data-border-style="<?= $block->getLogoThemeColour("product_detail_page")?>">
        </fam-osm>
        
    <?php endif; ?>
<?php endif; ?>  
