<?php
/**
 * Fam
 *
 * @category  Fam
 * @package   Fam_Fam
 * @author    Fam Team
 * @copyright Copyright (c) Frictionless Technologies Ltd (https://www.joinfam.com/)
 * @license   https://joinfam.com/legal
 */ 

/** @var $block \Fam\Fam\Block\OnsiteMessage */
?>
<?php if ($block->getWebsiteId()) : ?>
    <?php if ($block->isEnabled("product_detail_page")) : ?>

        <fam-osm data-widget-type="callout" data-currency="GBP" data-total-amount="<?= $block->getPriceById() * 100?>" data-theme="<?= $block->getThemeColour("product_detail_page")?>" data-border-style="<?= $block->getLogoThemeColour("product_detail_page")?>">
        </fam-osm>
        
    <?php endif;?>
<?php endif; ?>  
