<?php
/**
 * Fam
 *
 * @category  Fam
 * @package   Fam_Fam
 * @author    Fam Team
 * @copyright Copyright (c) Frictionless Technologies Ltd (https://www.joinfam.com/)
 * @license   https://joinfam.com/legal
 */ 

/** @var $block \Fam\Fam\Block\OnsiteMessage */
?>
<div charset="utf-8" id="fam.js" data-merchant-id="<?= $block->getMerchantId()?>" data-environment="<?= $block->getPaymentMode()?>"></div>
        
<?php if ($block->getWebsiteId()) : ?>
    <?php if ($block->isEnabled("checkout")) : ?>

        <fam-osm data-widget-type="callout"  data-currency="GBP" data-total-amount="<?= $block->getQuoteTotal()*100?>" data-theme="<?= $block->getThemeColour("checkout")?>" data-border-style="<?= $block->getLogoThemeColour("checkout")?>" data-key="product_and_cart">
        </fam-osm>

    <?php endif; ?>
<?php endif; ?>   
<script type="text/javascript">
    require(
        [
            "jquery",
            "https://cdnjs.cloudflare.com/ajax/libs/dialog-polyfill/0.5.6/dialog-polyfill.min.js",
            "https://cdnjs.cloudflare.com/ajax/libs/crypto-js/4.1.1/crypto-js.min.js"
        ], 
        function ($,dialogPolyFill,cryptoLib) {
            
    });
</script>

