<?php
/**
 * Ksolves
 *
 * @category    Ksolves
 * @package     Ksolves_Bankpay
 * @author      Ksolves Team
 * @copyright   Copyright (c) Ksolves India Ltd.(https://www.ksolves.com/)
 * @license     https://store.ksolves.com/magento-license
 */

/** @var $block \Ksolves\Bankpay\Block\OnsiteMessage */
?>
<?php if ($block->getWebsiteId()) : ?>
    <?php if ($block->isEnabled("cart_page")) : ?>
        
        <bankpay-osm data-cart-currency="GBP" data-amount="<?= $block->getQuoteTotal()?>" data-theme="<?= $block->getThemeColour("cart_page")?>" data-logo-theme="<?= $block->getLogoThemeColour("cart_page")?>" data-key="product_and_cart">
        </bankpay-message>

    <?php endif; ?>
<?php endif; ?>   
