<?php
/**
 * Ksolves
 *
 * @category    Ksolves
 * @package     Ksolves_Fam
 * @author      Ksolves Team
 * @copyright   Copyright (c) Ksolves India Ltd.(https://www.ksolves.com/)
 * @license     https://store.ksolves.com/magento-license
 */

/** @var $block \Ksolves\Fam\Block\OnsiteMessage */
?>
<?php if ($block->getWebsiteId()) : ?>
    <?php if ($block->isEnabled("cart_page")) : ?>
        
        <fam-osm data-widget-type="callout"  data-currency="GBP" data-total-amount="<?= $block->getQuoteTotal()*100?>" data-theme="<?= $block->getThemeColour("cart_page")?>" data-border-style="<?= $block->getLogoThemeColour("cart_page")?>" data-key="product_and_cart">
        </fam-osm>

    <?php endif; ?>
<?php endif; ?>   
