<?php
/**
 * Fam
 *
 * @category  Fam
 * @package   Fam_Fam
 * @author    Fam Team
 * @copyright Copyright (c) Frictionless Technologies Ltd (https://www.joinfam.com/)
 * @license   https://joinfam.com/legal
 */ 

/** @var $block \Fam\Fam\Block\OnsiteMessage */
?>
<?php if ($block->getWebsiteId()) : ?>
    <?php if ($block->isEnabled("mini_cart_popup")) : ?>

        <fam-osm data-widget-type="callout" data-currency="GBP" data-total-amount="<?= $block->getQuoteTotal()*100?>" data-theme="<?= $block->getThemeColour("mini_cart_popup")?>" data-border-style="<?= $block->getLogoThemeColour("mini_cart_popup")?>" >
        </fam-osm>
        
    <?php endif; ?>
<?php endif; ?>   
