<!--
 * Ksolves
 *
 * @category  Ksolves
 * @package   Ksolves_Fam
 * @author    Ksolves Team
 * @copyright Copyright (c) Ksolves India Limited (https://www.ksolves.com/)
 * @license   https://store.ksolves.com/magento-license
 */ 
-->
<?php
  $savedMethodsBlock = $block->getLayout()->createBlock('Ksolves\Fam\Block\Adminhtml\SelectPaymentMethod');
  $adminQuoteData = $savedMethodsBlock->getCurrentAdminQuote();
  $customer_email = $adminQuoteData->getData('customer_email');
  $grand_total = number_format($adminQuoteData->getData('grand_total'), 2, ".", "") * 100;

?>
<div class="fieldset indent" id="fam-area" style="display:none;">
  <script defer src="https://js.joinfam.com/v1/fam.js" charset="utf-8" id="fam.js" data-merchant-id="<?= $savedMethodsBlock->getMerchantId()?>" data-environment="<?= $savedMethodsBlock->getMode()?>"></script>
  <fam-checkout-button data-total-amount="<?= $grand_total ?>" data-currency="GBP" data-show-credits="true" data-theme="<?= $savedMethodsBlock->getThemeColour()?>"></fam-checkout-button>
  <input type="hidden" id="email" value="<?= $customer_email ?>">
</div>

<style type="text/css">
  #bkpy-info-id{
  pointer-events: none;
}
</style>

<script>
require(['jquery'], function($){
  $(document).ready(function(){
    // payment redio button change event
    $('body').on('change', 'input:radio', function(){
        if($(this).val() == 'fam'){
          $("#fam-area").show();
        }else{
          $("#fam-area").hide();
        }
    });
    // on fam button click
    $('body').on('click', '#btn-fam-checkout', function(event){
      
      var email = $('#email').val();
      $.ajax({
         url: "<?php echo $this->getUrl('fam/payment/merchantapi') ?>",
          type: "POST",
          data: {email:email},
          showLoader: true,
          cache: false,
          success: function(response){
            if (response.code==201) {
                doCheckout(response.data.checkout_id);
            } else {
                console.log('error');
            }
          }
      });
    });

  });
});
</script>
