<?php
/**
 * Fam
 *
 * @category  Fam
 * @package   Fam_Fam
 * @author    Fam Team
 * @copyright Copyright (c) Frictionless Technologies Ltd (https://www.joinfam.com/)
 * @license   https://joinfam.com/legal
 */ 

/** @var Fam\Deliverydate\Block\Sales\Order\View\DeliveryDateInfo $block */

$data = $block->getFamInformation();

?>
<div class="box-content fam-payment-info">
    <?php if ($data->getData('transaction_id')) : ?>
        <strong><?php echo __('Transaction Id:') ?></strong>
        <br><span><?= $data->getData('transaction_id') ?></span>
    <?php endif; ?>

    <?php if ($data->getData('transaction_status')) : ?>
        <br><strong><?php echo __('Transaction Status:') ?></strong>
        <span><?= $data->getData('transaction_status') ?></span>
    <?php endif; ?>
</div>

<script type="text/javascript">
    require(['jquery'], function ($) {
        $('.box-order-billing-method').append($('.fam-payment-info'));
    });
</script>
