<?php
/**
 * Ksolves
 *
 * @category    Ksolves
 * @package     Ksolves_Fam
 * @author      Ksolves Team
 * @copyright   Copyright (c) Ksolves India Ltd.(https://www.ksolves.com/)
 * @license     https://store.ksolves.com/magento-license
 */

/** @var $block \Ksolves\Fam\Block\OnsiteMessage */
?>
        
<?php if ($block->getWebsiteId()) : ?>
    <?php if ($block->isEnabled("checkout")) : ?>

        <fam-osm data-widget-type="success" data-currency="GBP" data-theme="light" data-border-style="<?= $block->getLogoThemeColour("checkout")?>">
        </fam-osm>

    <?php endif; ?>
<?php endif; ?>

