<?php
/**
 * Fam
 *
 * @category  Fam
 * @package   Fam_Fam
 * @author    Fam Team
 * @copyright Copyright (c) Frictionless Technologies Ltd (https://www.joinfam.com/)
 * @license   https://joinfam.com/legal
 */ 

/** @var $block \Fam\Fam\Block\OnsiteMessage */
?>
        
<?php if ($block->getWebsiteId()) : ?>
    <?php if ($block->isEnabled("checkout")) : ?>

        <fam-osm data-widget-type="success" data-currency="GBP" data-theme="light" data-border-style="<?= $block->getLogoThemeColour("checkout")?>">
        </fam-osm>

    <?php endif; ?>
<?php endif; ?>

